### ISSUE TITLE
Tìm hiểu đề tài và giao diện trang web Talk Desk

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#1]
- [x] 1. Tìm hiểu và phân tích đề tài
- [x] 2. Tìm hiểu phân tích các thành phần cơ bản của giao diện trang web Talkdesk
- [x] 3. Phân tích các thành phần của header, footer
- [x] 4. Phân tích các thành phần của nội dung chính và các phần phụ còn lại

**Comment by Quyen01022002** [comment]
đã hoàn thành

**Comment by Quyen01022002** [comment]
hoàn thành task
