### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#10]
- [x] 1. Purpose
- [x] 2. Document Conventions
- [x] 3. Intended Audience and Reading Suggestions
- [x] 4. Project Scope

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 1(28/03/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thanh Task 2(29/03/2023)

**Comment by Quyen01022002** [comment]
hoàn Thành Task 3(30/03/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 4(31/03/2023)
https://docs.google.com/document/d/12XyTlhIEPCjE4tdngTq067LCk43A_nh10ZNcuq_u470/edit?usp=sharing
