### ISSUE TITLE
Overall Description

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#11]
- [x] 1. Product Perspective
- [x] 2. Product Features
- [x] 3. User Classes and Characteristics
- [x] 4. Operating Environment
- [x] 5. Design and Implementation Constraints
- [x] 6. User Documentation
- [x] 7. Assumptions and Dependencies

**Comment by Quyen01022002** [comment]
hoàn thành task 1

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 2(29/3/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành Task 3 (30/3/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 4(31/3/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 1(31/03/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 2 (31/03/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 3 (1/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 4 (2/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 5 (2/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 6 (3/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn Thành Task 7 (4/4/2023)

Link Minh Chứng cho tất cả các task:https://docs.google.com/document/d/1cHzla-dolDzTPSghy6ApZJBK-MUAy7Br/edit?usp=sharing&ouid=101109999955777403445&rtpof=true&sd=true

**Comment by Quyen01022002** [comment]
Hoàn Thành
