### ISSUE TITLE
Deploy Project sử dụng Docker lên AWS

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#19]
- [x] 1. Tìm hiểu Docker
- [x] 2. Tìm hiểu các thành phần cơ bản của Docker
- [x] 3. Tìm hiểu AWS
- [x] 4. Tạo tài khoản trên AWS
- [x] 5. Tìm hiểu cách deloy project sử dụng Docker lên AWS
- [x] 6. Những thứ cần chuẩn bị để deloy 
- [x] 7. Cài đặt SpringBoot lên Docker

**Comment by Quyen01022002** [comment]
hoàn thành task 1(5/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 2(6/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 3(7/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 4(8/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 5(9/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 6(10/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành task 7(11/4/2023)

**Comment by Quyen01022002** [comment]
Hoàn thành link minh chứng:https://docs.google.com/document/d/1XQQc7SeeYKhL3vJ8f9YGXmW4SbbbndycLShSQZuTRqs/edit?usp=sharing
