### ISSUE TITLE
Tìm hiểu về Virtualization

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#21]
- [x] 1. Tầm quan trọng của Virtualization 
- [x] 2. Virtualization là gì
- [x] 3. Virtual Machine là gì
- [x] 4. Hypervisor là gì
- [x] 5. Virtualization hoạt động như thế nào
- [x] 6. Phân loại Virtualization
- [x] 7. Ưu nhược điểm của Virtualization
- [x] 8. Nhược điểm của Virtualization

**Comment by Quyen01022002** [comment]
Hoàn thành task 1

**Comment by Quyen01022002** [comment]
Hoàn thành task 2

**Comment by Quyen01022002** [comment]
Hoàn thành task 3

**Comment by Quyen01022002** [comment]
Hoàn thành task 4

**Comment by Quyen01022002** [comment]
Hoàn thành task 5

**Comment by Quyen01022002** [comment]
Hoàn thành task 6

**Comment by Quyen01022002** [comment]
Hoàn thành task 7

**Comment by Quyen01022002** [comment]
Hoàn thành task 8:
Link Minh Chứng: https://docs.google.com/document/d/1UrjYT57pGkyBYQKoUaoDRpoaLN9-mWe5WFDO1byYSX8/edit?usp=sharing
