### ISSUE TITLE
Lựa chọn ngôn ngữ, framework

### ISSUE THREAD

**Issue by Quyen01022002** [leanhnhandev/talk-desk-java-spring-boot#3]
- [x] 1. Chọn ngôn ngữ cho Front-end, Back-end (16/03/2023)
- [x] 2. Chọn framework cho Front-end, Back-end (17/03/2023)

**Comment by leanhnhandev** [comment]
Hoàn thành [Task 1, Task 2](https://docs.google.com/document/d/1aZo1O9wfpVY2wgEutdxcGrRCN6P3rTRM/edit)
