### ISSUE TITLE
Cấu trúc Frontend - ReactJs

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#4]
- [x] 1. Cài đặt IDE - Visual Studio Code
- [x] 2. Cài đặt Node
- [x] 3. Cài đặt Git
- [x] 4. Tạo project ReactJs
- [x] 5. Tải các thư viện cần thiết
- [x] 6. Cấu trúc lại các thư mục của project

**Comment by Quyen01022002** [comment]
đã cài đặt nha

**Comment by Quyen01022002** [comment]
Hoàn thành task: https://docs.google.com/document/d/1EDb0hAnR1pLDqYOJgTu5ivu168S0CgdFcH6v7eGEFvM/edit?usp=sharing

**Comment by Quyen01022002** [comment]
Đã cài đặt nodejs cập nhật ở link cmt trên

**Comment by Quyen01022002** [comment]
Đã cài đặt git về clone về máy

**Comment by Quyen01022002** [comment]
Đã tải các thư viện cần thiết

**Comment by Quyen01022002** [comment]
Đã hoàn thành task
