### ISSUE TITLE
Vẽ usecase diagram

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#7]
- [x] 1. Đặt tả usecase diagram - Đăng ký
- [x] 2. Đặt tả usecase diagram - Đăng nhập
- [x] 3. Đặt tả usecase diagram - Đăng xuất
- [x] 4. Đặt tả usecase diagram - Quên mật khẩu
- [x] 5. Đặt tả usecase diagram - Tìm kiếm
- [x] 6. Đặt tả usecase diagram - Gửi Tin Nhắn
- [x] 7. Đặt tả usecase diagram - Trả lời tin nhắn

**Comment by Quyen01022002** [comment]
đã hoàn thành

**Comment by Quyen01022002** [comment]
đã hoàn thành tất cả: https://docs.google.com/document/d/1Gb8-eduCnjVnT1B7fBmYalOOi8Afvi-zfohVB2PGYww/edit?usp=sharing
